version: '3'

services:
  gatewayservice:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    environment:
      - SPRING_APPLICATION_NAME=gateway-service
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      - consul

  userprofileservice:
    build:
      context: ./user-profile-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - SPRING_APPLICATION_NAME=user-profile-service
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sportepisen_DB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - consul
      - db


  mock:
    build:
      context: ./mock
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      - SPRING_APPLICATION_NAME=mock
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sportepisen_DB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - GATEWAY_HOST=gatewayservice:9999
    depends_on:
      - db
      - gatewayservice
      - heartratecollector

  consul:
    image: consul
    ports:
      - "8500:8500"
  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sportepisen_DB


  heartratecollector:
    build:
      context: ./heart-rate-collector-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=heart-rate-collector-service
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - consul
      - rabbitmq
      - gatewayservice


  notificationchannelmanagerservice:
    build:
      context: ./notification-channel-manager-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_APPLICATION_NAME=notification-channel-manager-service
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_REDIS_HOST=redis

    depends_on:
      - consul
      - rabbitmq
      - redis


  heartrateworker2:
    build:
      context: ./heart-rate-second-worker-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_APPLICATION_NAME=heart-rate-second-worker-service
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/sportepisen_DB
    depends_on:
      - consul
      - rabbitmq
      - mongo   


  heartrateworker:
    build:
      context: ./heart-rate-second-worker-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_APPLICATION_NAME=heart-rate-worker-service
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/sportepisen_DB
    depends_on:
      - consul
      - rabbitmq
      - mongo       

  emergencynotificationagentservice:
    build:
      context: ./emergency-notification-agent-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_APPLICATION_NAME=emergency-notification-agent-service
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sportepisen_DB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - consul
      - rabbitmq
      - db   


  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"

      
  redis:
    image: redis
    ports:
      - "6380:6379"    
      
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"

volumes:
  db_data:
  mongo_data:





  
version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


version: '2'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic:1:3"