FROM openjdk:17
# Set the working directory
WORKDIR /app

# Copy the jar file to the working directory
COPY target/*.jar emergencynotificationagentservice.jar




# Run the application
CMD ["java", "-jar", "emergencynotificationagentservice.jar"]