FROM openjdk:17
EXPOSE 8085
COPY target/emergency-notification-agent-service-docker.jar emergency-notification-agent-service-docker.jar
ENTRYPOINT ["java","-jar","/emergency-notification-agent-service-docker.jar"]