FROM openjdk:17
EXPOSE 8083
COPY target/heart-rate-second-worker-service-docker.jar heart-rate-second-worker-service-docker.jar
ENTRYPOINT ["java","-jar","/heart-rate-second-worker-service-docker.jar"]